export const cards = {
  name: 'alap',
  white: [
    'Öregemberszag',
    'Mikropénisz',
    'Használt bugyik',
    'Osztrály-sznob felhangok',
    'Leszarni Baranyát',
    'Telefonszex',
    'Egy tokaji borospincényi hulla',
    'A buzik',
    'Egy túlméretezett nyalóka',
    'Nyóckeres purdék',
    'Egy elcseszett mellpalsztika',
    'Egy macskahúggyal teletankolt vízágyú',
    'Egy jó kis Ödipusz-komplexus',
    'Egy picsányi póni',
    'Péniszirigység',
    'Orbán Viktor',
    'Soros György',
    'A doborulataim',
    'Félmeztelenül felébredni egy benzinkúton',
    'Szcientológia',
    'Öklendezés',
    'Paralgfűirtás',
    'Darth Vader',
    'A Danone görög joghurtos pornószínésznők',
    'Öregecske japán fickók',
    'Ingyenes kóstoló',
    'Ösztrogén',
    'Szexuális frusztráció',
    'Éhinség',
    'Egy kóbor fanszőr',
    'Pasik',
    'Szívfacsaró árvák',
    'Intim testékszer',
    'Egy szütyőnyi varázsbab',
    'Elnyomás',
    'Ügetés',
    'A kapcsolati állapootom',
    'Agyonkompenzálás',
    'Bepisilni',
    'EGy vöröske szelős herezacskója',
    'Herecsavarodás',
    'Maga az Ördög',
    'WoW',
    'Egy kis kibaszott béke és nyugalom',
    'Robo-Hitler',
    'Cicifotók',
    'Gyengéd simi a bikinivonalon',
    'Kitörölni a csajod seggét',
    'Lance Armstrong hiányzó heréje',
    'Magyarország',
    'Az ex-feleségem',
    'Szexi párnacsaták',
    'Egy újabb kibaszott csillámvámpíros film',
    'Kibernatikus implantációk',
    'Civil áldozatok',
    'A női orgazmus',
    'Ribancok',
    'Auschwitz',
    'Ujjfestés',
    'A zsidók',
    'Kiközösítés',
    'Krisztus vére',
    'Elhunyt szülők',
    'A csábíttás művészete',
    'Vérhasban meghalni',
    'Erdély',
    'Tarlós István pocakját simogatni amíg elszundikál',
    'Földművelés',
    'Megelepetésszex',
    'Homoszexuális propaganda',
    'Gina',
    'Millió nap fénye',
    'Amputáltak',
    'Szűzet dobni a vulkánba',
    'Olaszok',
    'Robbanások',
    'Egy mély szippantás',
    'Eltüntetni a bizonyítékot',
    'Gyerekek pórázon',
    'Katapultok',
    'Ezer csillió forint',
    'Haldokolni',
    'Csönd',
    'Fluor Tomi',
    'A Szent Bibilia',
    'Golyók',
    'Fohászkodni a buzik ellen',
    'Tini terhesség',
    'Német kakipornó',
    'A belső démonaim',
    'Erőtől duzzadó combok',
    'Egy széthipózott segglyuk',
    'Svájcifrankhitel',
    'Kamikáze pilóták',
    'Rendőrállom',
    'Lóhús',
    'A cserkészek',
    'Michael Jackson',
    'Egy nagyon pöpec kalap',
    'Kristálymet',
    'Alakváltók',
    'Ujjazás',
    'Egy várakozáson aluli szülinapi party',
    'A lelkem',
    'Eugenetika',
    'Szinergetikus menedzsment metódus',
    'Összegabalyodott Slinky rugók',
    'Köznevetség tárgya',
    'Csajozni az abortuszklinikán',
    'Lovagiasság',
    'Magaviselet',
    'Elfogadható transzvesztiták',
    'Nedves álmok',
    'Pandaszex',
    'Mekrofília',
    'Sírrablás',
    'Mohamed (Áldassék a neve)',
    'Fityamfattyú',
    'Elő stúdióközönség',
    'Durcás arcot vágni',
    'A legalapvetőbb emberi jogaink megsértése',
    'Mérhetetlenül mély butaság',
    'Bolyhos nyuszik, szivárvány és napsütés',
    'Előcsapni',
    'Terroristák',
    'Csalni a paralimpián',
    'Egy zsémbes teknőc, ami leharapja a fütyid végét',
    'A nagy gazdasági világválgás',
    'Érzelmek',
    'Annyira bedühődni, hogy feláll tőle a farkad',
    'Azonos nemű műjégkorcsolyázás',
    'Báármi, amit Torgyán József kiejt a száján',
    'Emberhús',
    'Vérfertőzés',
    'A helyes dolgot tenni',
    'Amikor púzol, és egy kicsi kijön',
    'Pajkoskodás',
    'Köcsögösködni gyerekekkel',
    'Erzsébet királynő makulátlan ánusza',
    'A fekete halál',
    'Keselyűtámadások',
    'Lecsapás',
    'Hanyag előjáték',
    'Teljes frontális meztelenség',
    'Pengeélesre fagyott mellbimbók',
    'Kergemarha',
    'Szájherpesz',
    'Egy megtermett mongoloid',
    'Kölcsönösen biztosított megsemmisítés',
    'Egy puncipuki',
    'Sztálin',
    'Szoptatás',
    'A karácsony igazi értelme',
    'Önutálat',
    'Agydaganat',
    'Kimúlt babák',
    'Termonukleáris detonáció',
    'Libák',
    'Úri faszverés',
    'Isten',
    'Harry Potteres Playboy',
    'Seggrákos gyerekek',
    'Favágófantáziák',
    'Az amerikai álom',
    'Pubertás',
    'Édes, édes bosszú',
    'Idős emberekre kacsintgatás',
    'Véreshurka',
    'Pasik, akik sosem hívnak utána',
    'Erektilis diszfunkció',
    'Kettéválasztani a Vörös tengert',
    'Huncut popsiszex',
    'Egy szaxofonszóló',
    'Taposóaknák',
    'Jehova tanúi',
    'Egy kis kikapcsolódás',
    'Szembefordítható hüvelykujjak',
    'Szellemek',
    'Alkoholizmus',
    'Rosszul időzített holokaisztviccek',
    'Alkalmatlan jódlizás',
    'Harctéri amputációk',
    'Pontosan amire gondolnál',
    'Időparadoxon',
    'Mocskos száj',
    'Kellemetlen üzenetet hagyni az üzenetrögzítőn',
    'Egy kibaszott boszorkány',
    'Egy sólyom sapkával a fején',
    'Fingani, majd arrébsomfordálni',
    'A kínai tornászcsapat',
    'Hüvelygomba',
    'Megnyalni dolgokat, hogy aztán megtarthasd őket',
    'Vikingek',
    'Nicholas Cage',
    'Egy lyukas óvszer',
    'Az Univerzum elkerülhetetlen hőhalála',
    'Csápos pornó',
    'Lomtár',
    'Apuci problémák',
    'Egy pantomimes, aki szívrohamot kap',
    'Fehér emberek',
    'Egy életre elegendő szomorúság',
    'Ízléses oldalcsöcs',
    'Nácik',
    'Egy szervekkel tömött ribanc',
    '110%-ot beleadni',
    'Rejtegetni egy erekciót',
    'Irdatlan dagadtság',
    'Kiskutyusok',
    'Természetes férfierő',
    'Túl forró leves',
    'Pornósztárok',
    'Hormoninjekció',
    'Kihúzni utána',
    'Egy AK-47-es géppisztoly',
    'Kifordítva viselni az alsóneműt, csak hogy ne kelljen mosni',
    'Rehab',
    'Egy magzat',
    'Nem viszonozni az orális szexet',
    'Extasy',
    'Szexi srácok',
    'Fityma',
    'A Jobbik',
    'A gyermekáldás csodája',
    'Az esküvőig várni',
    'Orbán Viktor',
    'Rosszkedvű maszturbálás',
    'Épccsak megérinteni David Beckham haját',
    'Tényleg nagyon szűk nadrág',
    'Szákvíztől berúgni',
    'Dalban és táncban kitörni',
    'Sámánok',
    'Egy vita Richard Dawkinsszal',
    'A szlovákok',
    'Koszos pelusok',
    'Németek nyaraláson',
    'Remény',
    'Levenni az ingedet',
    'A One Direction tagok hamvas, zsenge, sima testei',
    'Etnikai tisztogatások',
    'Pedofilok',
    'Nagyon-nagyon betépni',
    'Természetes kiválasztódás',
    'Egy púzó antilop',
    'A szexuális életem',
    'Arnold Schwarzenegger',
    'Törődést tettetni',
    'Kimondani azt, hogy "útelágazódás"',
    'Egy ocsmány arc',
    'A halálsugár',
    'BATMAN',
    'Hajléktalanok',
    'Kentaurok',
    '72 szűz',
    'Emberióőssejtek',
    'Pixeles bukkake',
    'Seppuku',
    'Jégcsákányos lobotómia',
    'Birodalmi lépegető',
    'Menstruációs düh',
    'Kipréselni egy vesekövet',
    'Elborzasztó lézeres hajeltávolító melléfogások',
    'Önkannibalizmus',
    'Kiverni a kekszet egy árva szájából',
    'Ellovagolni a naplementébe',
    'Koboldok',
    'Fényes tárgyak',
    'Gazdagság',
    'Lepre',
    'Világbéke',
    'Faszujjak',
    'Láncfűrész a kezek helyett',
    'Britney Spears, 55 évesen',
    'Tojni',
    'A nemiszervem',
    'Nagymami',
    'Húsevő baktériumok',
    'Szegény emberke',
    '50 000 volt egyenesen a mellbimbókba',
    'Elhibázott döntések az életben',
    'Oltárfiúk',
    'A vaginám',
    'Technokolt szippantani',
    'Méhlepény',
    'A halmozottan hátrányos helyzetűek',
    'Magyar Hajnal',
    'A csikló',
    'Tökéletes kakaóscsigát szarni',
    'Szex, közös beleegyezéssel',
    'Feketék',
    'Egy vödör csirkelsőség',
    'Passzív-agresszív üzenetek',
    'A Bartók Közt teljes stábja',
    'Gyerekszív',
    'Tűn osztozni',
    'Kövérnek és butának lenni',
    'Büfizésre számítani, de mégis sugárban hányni',
    'Asszonyi kötelességek',
    'Attila, a hun',
    'Édes-savanyú kaki',
    'Keresztre feszítés',
    'AIDS',
    'Ehető alsónemű',
    'Az ultamodern szexjátékgyűjteményem',
    'Az Erő',
    'Független Kisdgazdák',
    'Maszturbálás',
    'Tom Cruise',
    'Egy kiegyensúlyozott reggeli',
    'Egyedül ivás',
    'Emeberi Elleni Kéártyák',
    'Abortusz horgolótűvel',
    '150 évnyi török elnyomás',
    'Összebújni',
    'Egy bögre meleg tea',
    'Bányabalesetek',
    'Kulka János hangja',
    'Egy rollerező középkorú',
    'Gandhi',
    'Szemkápráztató kockahas',
    'Keanu Reeves',
    'Gyermekmolesztálás',
    'Tudomány',
    'Viagra(R)',
    'Őfelsége, I. Viktor',
    'Ahogy James Bond bánik a nőkkel',
    'Négy óránál hosszabb erekció',
    'Disznósajt',
    'Véreshurkás óvszer',
    'HAZAÁRULÓ',
    'Trianon',
    'Hatvannégy vármegye',
    'Matolcsy kancsal tekintete',
    'Kackiás magyar levente',
    'Kálmán Olga fehérneműben',
    'A Szent Korona',
    'Ady Endre szifilisze',
    'Két kicsi LEGO',
    'Pártunk és vezetőnk',
    'A nagymama',
    'Ádes János bajsza',
    'Rubik kocka',
    'A békemenet',
    'Plutóniumos nyalóka',
    'Kis piros pötty',
    'Vaníliás karika',
    'Spermafőzelék',
    'Az új Széchényi terv',
    'A Gurcsány',
    'Luxusproletár',
    'Balázs Pali',
    'Kergemarhakór',
    'Vona Gábor melegbárban',
    'Kommunisták',
    'Esemény helyetti tabletta',
    'A kilencfordulatú DNS-ű turulmadár',
    'Kivenni az edényeket egy csapból, mielőtt belehugyozol',
    'Paks',
    'Obersovszky nyelve',
    'Komcsi',
    'Csángó himnusz',
    'Disznóvágás',
    'Hungarisztán',
    'Nem hiszem',
    'A faszom',
    'Légmell',
    'Vak komondor',
    'Idegenredészeti eljárások',
    'Semjén János',
    'Balrog Zoltán',
    'Felcsút',
    'Lézer János',
    'Lepra',
    'Betyárkörte',
    'Kozákkucsma',
    'Két vödörbe szaró törpe',
    'Rasszizmus',
    'Nők a joghurt reklámokban',
    'Osztályharc',
    'Lezsarni a visszamaradott országokat',
    'Egy szélmalom tele hullákkal',
    'Az indiánok',
    'Túlméretezett nyalóka',
    'Aftikai gyerekek',
    'Fika',
    'Bajnai Gordon',
    'A seggem',
    'Öklendezés',
    'Termékminta',
    'Öreg kínaiak',
    'Piercing a nemi szervemben',
    'Elnyomás',
    'A kapcsolati státuszom',
    'Az egyetlen cigány barátom',
    'Bepisilni egy kicsit',
    'Ordítva hányni',
    'Herecsavarodás',
    'Az ördög maga',
    'Egész álló nap fosni',
    'World of Warcraft',
    'Keverni a szart',
    'A pápa',
    'Repülő péniszek',
    'Kibernetikus életminőségjavítás',
    'Megmosni a hajlatokban is',
    'Szájjal festés',
    'Gondos bocsok',
    'Kisebbséghez tartozni',
    'Halott szülők',
    'A csábítás művészete',
    'Mr. Muscle, MÖGÖTTED!',
    'Munkatábor',
    'Mélymagyar HÖK-ösök',
    'Sthol András',
    'Mezőgazdaság',
    'Mónika',
    'A honfoglalás',
    'Hajdú Péter',
    'Románok',
    'Haldoklás',
    'Jó mélyen beszippantani',
    'Odébb imádkozni egy buzit',
    'Erős combok',
    'Meztelenül nézni a Nóta TV-t',
    'Terhes tinilányok',
    'Német szadopornó',
    'Heteronormativitás',
    'Családon belüli erőszak',
    'Heroin',
    'Krokodil',
    'Viktatúra',
    'Ujjazás',
    'Cigánywellnesz',
    'Fila táska',
    'Cirmantás',
    'Állófogadás',
    'Vészfasz',
    'Bömös',
    'Egy laza petting',
    'Parizercsöcs',
    'Nokiásdoboz',
    'Análfűrész',
    'Geciputtony',
    'Fasztarisznya',
    'Csurka István hullamerevsége',
    'Fábry Sándor szájszaga',
    'ATM',
    'Fásy Zsülika véres bugyija',
    'Kiszel Tünde szemöldökszőrtüszőgyulladása',
    'Fitymatestvériség',
    'Viva TV-re recskázni',
    'Egy meleg KDNP-s öngyűlölete',
    'Nemzeti Dohánybolt',
    'Anikó az Éjjel-nappal Budapestben',
    'Liftbefingás',
    'Kézcölibátus',
    'SP coming outja',
    'Matolcsy igéző tekintete',
    'Hofi Géza hamvai',
    'Steve Jobs hasnyálmirigye',
    'Lúgosító fehérkávé Zambiából',
    'Pénzenergia',
    'Bangó Margit súlyfeleslege',
    'Fásy Ádám önbizalma',
    'Mélymagyarság',
    'Cigányozni Borsodban'
  ],
  black: [
    {text: 'Hogyan vesztettem el a szűzességem?', cards: 1 },
    {text: 'Miért nem jön álom a szememre?', cards: 1 },
    {text: 'Mi ez a szag?', cards: 1 },
    {text: 'Lehet, hogy veleszületett.... Lehet, hogy ____.', cards: 1 },
    {text: 'Mi jár a Happy Meal mellé?', cards: 1 },
    {text: 'Kár, hogy a mai gyerekek csak a ____-ra/re tudnak gondolni.', cards: 1 },
    {text: 'Salvadort Dali gyermekkori képeinek százai szólnak ____-ról/ről.', cards: 1 },
    {text: 'A legújabb  alternatív gyógymód már kihasználja a(z) ____ gyógyító erejét.', cards: 1 },
    {text: 'Mi ez a hang?', cards: 1 },
    {text: 'Mi vetett véget a legutolsó kapcsolatomnak?', cards: 1 },
    {text: 'Iszom, hogy felejtsem: ____.', cards: 1 },
    {text: 'Mi Batman titkos fétise?', cards: 1 },
    {text: 'Apu, miért sír anyu?', cards: 1 },
    {text: 'Egy gondolat bánt enegemet: ____ által halni meg.', cards: 1 },
    {text: 'A következő bűvészmutatványomban elővarázsolom ____-t ____-ból/ből.', cards: 2 },
    {text: 'Elnézést tanár úr, de nincs kész a házifeladatom ____ miatt.', cards: 1 },
    {text: 'Az oroszok már a ____-ben vannak!', cards: 1 },
    {text: '____: megírom.', cards: 1 },
    {text: 'Az igazui KDNP-s a havi 47 ezer forintból ____-t venne először.', cards: 1 },
    {text: '____: nem fog fájni.',cards: 1 },
    {text: '____: nem kicsit, nagyon.', cards: 1 },
    {text: '____: kúrnám.', cards: 1 },
    {text: 'Van egy régi mániám: ____kel végigmenni Románián.', cards: 1 },
    {text: 'Hiszek egy istenben, hiszek egy hazában, hiszek ____ feltámadásában.', cards: 1 },
    {text: 'Szex közben szeretek a ____-ra/re gondolni', cards: 1 },
    {text: 'Mit rejtegetnek előlem a szüleim?', cards: 1 },
    {text: 'Mi biztosít garantált szexet?', cards: 1 },
    {text: 'A reptéri biztonsági előírások monstantól megtiltják a ____ fedélzetre vitelét', cards: 1 },
    {text: 'Mitől fogok megfékezhetetlenül fingani?', cards: 1 },
    {text: 'Milyen szaguk van az öregeknek?', cards: 1 },
    {text: 'Mostantól a Mikulás virgács helyett ____-t hoz a rossz gyerekeknek.', cards: 1 },
    {text: 'Életében egyetlen dolgot írt le helyesen Schmitt Pál: ____.', cards: 1 },
    {text: '____: Magyarország jobban teljesít!', cards: 1 },
    {text: 'Neked is egy trafik: ____.', cards: 1 },
    {text: 'Egyetlen emlékem a tavalyi Szigetről: ____.', cards: 1 },
    {text: 'Hello Tourist, du bust in Budapest, /Capital of Hungary. / For a little money, I will show you ____', cards: 1 },
    {text: '____: én így szeretlek.', cards: 1 },
    {text: 'Addig üsd a ____-t, amíg ____.', cards: 2 },
    {text: 'Áder Jánod csak egy dolgot szeret jobban a bajszánál: ____-t.', cards: 1 },
    {text: 'A következő botrány: ____-mutyi!', cards: 1 },
    {text: 'Kicsi a(z) ____, de szar az íze.', cards: 1 },
    {text: '____: reggel, éjjel, meg este.', cards: 1 },
    {text: 'Mi az amit jobb adni, mint kapni?', cards: 1 },
    {text: 'A mai téma az Egyenes Beszédben Kálmán Olgával: ____.', cards: 1 },
    {text: 'Nagypapi újabban ____-ból/ből csinál pálinkát.', cards: 1 },
    {text: 'Hé, ____, melyik út megyen itt Budára?', cards: 1 },
    {text: '____ meg a fia fát vágnak az erdőben.', cards: 1 },
    {text: 'A hazug ____-et hamrabb elviszi a NAV, mint a sánta ____-et.', cards: 2 },
    {text: '____ és ____ egy illegális disznóvágás hevében jöttek össze.', cards: 2 },
    {text: '____ inkább ____-et vinné föl a padlásra.', cards: 2 },
    {text: 'A korszakváltó új párt: Lehet Más a(z) ____.',  cards: 1 },
    {text: '____ és ____: együtt tették tönkre az országot!', cards: 2 },
    {text: 'Ha egyetlen dolgot válaszhatna, mit vinni magával Orbán Viktor egy lakatlan szigetre?', cards: 1 },
    {text: 'Mi Gyúrós Józsi kedvence?', cards: 1 },
    {text: 'Más faszával veri a ____-t.', cards: 1 },
    {text: 'Jó volt ez a ____, csak egy kicsit kevés volt!', cards: 1 },
    {text: 'Milyen szuperképességem van?', cards: 1 },
    {text: 'Mi az anti-drogom?', cards: 1 },
    {text: 'Mi lesz a következő meglepetés a Kinder tojásban?', cards: 1 },
    {text: '99 problémám van, de a(z) ____ nem tartozik közéjük.', cards: 1 },
    {text: 'Nem tudom, hogy a harmadik világháborúban milyen fegyverekkel fognak harcolni, de a negyedikben csak ____ fegyverek lesznek.', cards: 1 },
    {text: 'Egy világban, amelyet elpusztít a(z) _____, az egyetlen reménységünk a(z) ____.', cards: 2 },
    {text: 'Kutatások bizonyítják, hogy a kisérleti patkányok 50%-kal gyorsabban találnak ki a labirintusból ____ hatása alatt.', cards: 1 },
    {text: 'Igen, megöltem ____-t, Hogyan? ____', cards: 2 },
    {text: 'Miért fáj mindenem?', cards: 1 },
    {text: 'Az amerikai indánok élete örökre megváltozott, amikor a fehérek megmutatták: ____', cards: 1 },
    {text: 'Mivel motiválják Borsodban a 3H-s diákokat a tanulásbra?', cards: 1 },
    {text: 'Mi az amitől a nagyi kiborulna, mégis elbűvölőnek találná?', cards: 1 },
    {text: '____ + ____ = ____', cards: 3 },
    {text: 'Azt mondják, hogy Vlagyimir Putyin kedvenc finomsága a(z) ____, ____ töltelékkel.', cards: 2 },
    {text: 'Az idei Oscar-díj nyertese ____, a(z) ____ című filmben nyújtott alakításáért.', cards: 2 },
    {text: 'Amíg az Egyesül Államok a Szovjetunióval versenyzett a holdig, a mexikói kormány több millió pezót költött kutatásokra a(z) ____ területén.', cards: 1 },
    {text: 'Nem értettem igazán a(z) ____ fogalmát, amíg bele nem botlottam ____-ba/be', cards: 2 },
    {text: '____: az életem adnám érte.', cards: 1 },
    {text: 'Rakj össze egy haikut', cards: 3 },
    {text: 'Hogyan lazít Viktor', cards: 1 },
    {text: 'Amikor én leszek a miniszterelnök, létrehozom a(z) ____ miniszériumot.', cards: 1 },
    {text: 'Mi a legginkább emo?', cards: 1 },
    {text: 'Mitől ragadok?', cards: 1 },
    {text: 'Azért iszom, hogy felejtsem ____-et.', cards: 1 },
    {text: 'Amikor milliárdos leszek, harminc méteres szobrot emelek ____ emlékére.', cards: 1 },
    {text: 'Mitől nem tudok éjszaka aludni?', cards: 1 },
    {text: '____. Így akarok meghalni.', cards: 1 },
    {text: 'A földrengés után Sean Penn ____-et vitt a Haitin élő embereknek.', cards: 1 },
    {text: 'Kedves Mónika! Szeretnék szerepelni a műsorodban, mert problémáim vannak ____-el kapcsolatban.', cards: 1 },
    {text: 'Egy gyertyafényes, romantikus vacsora nem lenne teljes ____ nélkül.', cards: 1 },
    {text: '1000 év múlva, amikor a pénz intézménye már csak távoli emlék lesz, ____ segítségével fizetünk majd.', cards: 1 },
    {text: 'A Természettudományi múzeum új interaktív kiállításának címe: ____', cards: 1 },
    {text: 'Miről mondok le a böjt alatt?', cards: 1 },
    {text: 'A következő mutatányomban előhúzok egy ____-t a ____-ból/ből.', cards: 2 },
    {text: 'Mi ez a szag?', cards: 1 },
    {text: 'Mit vinnél magaddal a múltba, hogy meggyőzd az embereket arról, hogy varázsló vagy, aki bármire képes?', cards: 1 },
    {text: 'Így lesz vége a világnak.', cards: 1 },
    {text: '____. Pacsi!', cards: 1 },
    {text: 'Az alternatív orvoslás most a(z) ____ gyógyító erejét fogadta el.', cards: 1 },
    {text: 'Mi a lányok legjobb barátja?', cards: 1 },
    {text: 'M. Night Shyamalan új filmjében Bruce Willis rájön, hogy ____ valójában ____ volt mindvégig.', cards: 2 },
    {text: '____. Magas élet.', cards: 1 },
    {text: 'Ebben az évadban a Broadwy-en bemutatják: ____, a Musical.', cards: 1 },
    {text: 'Mit evett Vin Diesel vacsorára?', cards: 1 },
    {text: 'Kazincy kedenv szava a 21. századból ____ lenne.', cards: 1 },
    {text: 'Mi a legújabb diétaőrület?', cards: 1 },
    {text: '____: gyerekek tesztelték, anyák hagyták jóvá.', cards: 1 },
    {text: 'Az osztálykirándulást teljesen elrontotta a(z) ____.', cards: 1 },
    {text: 'Sajnálatos, hogy a mai fiatalok olyan dolgokkal foglalják le magukat, mint a(z) ____.', cards: 1 },
    {text: 'J.K. Rowling új könyvének a címe: Harry Potter és a(z) ____.', cards: 1 },
    {text: 'Amikor rendkívül be voltam gombázva, akkor ____ átváltozott és ____ lett.', cards: 2 },
    {text: 'Mi ez a hang?', cards: 1 },
    {text: 'Mi az amit nem szeretnél megtalálni a kínai kajádban?', cards: 1 },
    {text: 'Az Nb I-ben betiltották, mert tisztességtelen előnyhöz juttatta a csatárokat.', cards: 1 },
    {text: 'Azt mondják, h ogy a szegedi CSillag börtönben 10 doboz cigiért kaphatsz ____-t', cards: 1 },
    {text: 'A fehér emberek szeretik ____-t', cards: 1 },
    {text: 'A Viasat új reality-jében lejáratott celebek szerepelnek rengeteg ____ társaságában.', cards: 1 },
    {text: 'Az X-Faktor győztese kiadata első lemezét, melynek címe: ____.', cards: 1 },
    {text: 'A Disney úk filmjében Hannah Montana életében először küzd meg ____-el.', cards: 1 },
    {text: 'Mit részesít előnyben Marvcai Krisztina?', cards: 1 },
    {text: 'Mi lesz a következő játék a Happy Mealben?', cards: 1 },
    {text: 'Mi lesz a korral egyre jobb?', cards: 1 },
    {text: '____ egyenes út ____ felé.', cards: 2 },
    {text: 'Apu! Miért sít anyu?', cards: 1 },
    {text: 'Mielőtt megölöm Önt, Mr. Bond, megmutatom magának a(z) ____-t', cards: 1 },
    {text: 'Első lépés: ____. Második lépés: ____. Harmadik lépés: Profit.', cards: 2 },
    {text: 'Mi Batman titkos szenvedélye?', cards: 1 },
    {text: 'Mit hoztam haza mexikóból?', cards: 1 },
    {text: 'Hogy híváj majd a következő szuperhőst?', cards: 1 },
    {text: 'Most következik az Eurosporton: ____ világbajnokság.', cards: 1 },
    {text: 'Göncz Árpád volt köztársasági elnök kedvenc dalának címe: ____.', cards: 1 },
    {text: 'József Attila: ____.', cards: 1 },
    {text: 'A Nemzeti érzelmű motorosok tüntetésén jelenlévők egy emberként skandálták: ____!', cards: 1 },
    {text: 'Magyarország egyetlen reménye a(z): ____.', cards: 1 },
    {text: 'Amikor legközelebb szexelni fogok, azért nem fogok tudni majd elmenni, mert folyton eszembe jut közben a(z) ____.', cards: 1 },
    {text: 'A pápa a karácsonyi mise után megáldott a a(z) ____-et a szeretet ünnepe alkalmából.', cards: 1 },
    {text: 'A büszkeség a lélek ____-je.', cards: 1 }
  ]
}

export const cards2 = {
  name: 'kft',
  white: [
    'Ingyenes Motivációs Előadás',
    'First AIDS kit',
    'DJ BENZINTANK - 3as metróval közösen szétesős bennégős mix',
    'Gyapotföld',
    'ITS WEDNESDAY MY DUDES!',
    'Cica Imádók Közössége - Együtt a Felelős Cicatartásért',
    'Kommunáci :)',
    'Megtalálni magadat a DarkWeben 70%-os leárazással',
    'Csak 12 piña colada',
    'Google Chrome Incognito Mode',
    '༼ ºل͜º༼ ºل͜º༼ ºل͜º ༽ºل͜º ༽ºل͜º ༽ ＥＶＥＲＹＯＮＥ，ＧＥＴ ＩＮ ＨＥＲＥ ༼ ºل͜º༼ ºل͜º༼ ºل͜º ༽ºل͜º ༽ºل͜º ༽',
    'ROBLOX videósok',
    'NDK-s hűtőszekrények még 1970-ből',
    'Fasiszta Luxemburg',
    '4K ULTRAHD',
    '360 MLG NOSCOPE',
    '25 kill streak! Press 6 for TACTICAL NUKE',
    '❤',
    'Kijátszani a Witcher III-at... Tizenharmadjára...',
    'Operation fuckdefenders',
    'ELMO SZINTETIKUS VILÁGA',
    'Augusztusz Ámesz',
    'LIDL táblába frontálisan belemenni, miközben egy bevásárlókocsiban tolnak',
    'Csak 12 sör',
    'Alqadidas',
    'Kiszaltózni a hintából',
    'Bekerülni Troldenbe',
    'Topdeck!',
    'Hanging Park',
    'Behozni egy élő kakast az iskolába karácsonykor',
    'Elírni, hogy Send Nudes  Send Nukes-ra',
    'HOI4',
    'Robo bitch',
    'Véletlen visszafoglalni Kárpátalját',
    'Brutálisan összetörni egy Renault Meganet egy kurva macska miatt',
    'Csehszlovák olcsó tankok',
    '45 perc.  Érintés nélkül!',
    'Samsung Galaxy C4',
    'Need for speed: most Wehrmacht',
    '☐ Not REKT ☑ REKT',
    'Next level ASMR',
    'Berlin-Moszkva Tengely',
    'VAPE ME UP! VAPE ME UP INSIDE',
    '#72-estátratea',
    '▶ 🔘──────── 00:23',
    'Minecraft Túlélő sorozat ep. 1',
    'Tumblr lányokkal randizni',
    'Amerikai katonák és az olaj',
    'Mátészalka Aquapark',
    '1080p 60FPS',
    'Tesla az űrben',
    'Borgödör',
    'Gyütyül gang',
    'Honda JAZZ',
    'Top 10 kivégzés',
    '☭☭☭☭☭☭☭☭☭☭☭☭☭',
    'Pozsonymelléki Általános Iskola és Gimnázium tiszteletbeli tagja',
    'Erotikus zabálás hangok miközben a mikrofon 1,4 cm-re helyezkedik el a csücskös ajkaktól',
    'XDDDDDDDDDDDDDDDDDDDDDDDDDD',
    'Csirke vacsora',
    'Virágvasárnap',
    'Bezárva egy liftbe 41 óráig',
    '1 139 844.92 kacsaerős traktor',
    'Fortnut.exe',
    'Bitcoin, a digitális fizetőeszköz',
    'Nyugi, Németország nyerte a 0. világháborút',
    'Majdnem egy csecsemő',
    'Get CSICSKD',
    'Lafi-Kobra',
    'Kommunáci',
    'Tüzesen süt le a nyári nap sugára Az ég tetejéről a juhászbojtárra. Fölösleges dolog sütnie oly nagyon, A juhásznak úgyis nagy melege vagyon',
    'Jókai More',
    'Ingyen V-Bucks',
    'Hitelkártya',
    '6 millió nem volt elég',
    'Megyek, kirabolom a Miskolci Media Marktot',
    'Dominik, a fekete árus',
    'VÉÉÉÉÉÉÉÉÉR',
    'A Berlini fal második felavatása',
    'Ugandai Knuckles',
    'Területcentrikus Oszmán Gazdaság',
    'Nincs erre jó lapom, ezért tessék itt egy vicc: Mi a közös az Urológus és az Uránbányász között? Mindketten erősen szennyezett helyen dolgoznak',
    'Drogobert bácsi kacsameséi',
    'Lolikkal játszani',
    'Durex reklám után elaludni a kanapén',
    'Csak még 1 árva WoW napiküldetés anya, nem több, ígérem',
    'Vallásos Minecraft Szerver',
    '60 köbliter mentolos banános cukros liquidbe belefulladni',
    'ÉN VESZEM MEG AZ AKCIÓS HURKÁT',
    'Amerikai-német akciófilm, kalandfilm, szerelmi történet, vígjáték',
    'Dabelni miután elment a csaj (is végre 30 perc + ujjazás után....)',
    'Honnan a faszomból esik ez a szar amikor hétágra süt a nap hogy kúrjam beléd vissza te',
    'Közös hazasétálás Szlovákiába Robival, az abonyi medvével',
    'Mennyei megyei',
    'وسمسمصززيني',
    'Hello am 48 year man from somalia. Sorry for my bed england. I selled my wife for internet connection for play &quot;conter strik&quot; and i want to become the goodest player like you I play with 400 ping on brazil server and i am global elite 2. pls no copy pasterio my story',
    'Az urán felezési ideje',
    'Szíria: Battle Royal',
    'A rák aki kalózokat eszik',
    'Etióp Új-Zéland',
    'Olaszország a 2018-as világbajnokságon.  Oh, várjunk csak.....',
    'Szenegál 1960-as függetlenedése',
    'McDonalds Die Through',
    '300 ft-os KonzolVilág kupon',
    'Bocs, van barátom',
    'A martonvásári háromcsillagos hotel 12. szobája',
    'Az autizmus nem létezik. Akiket ti autistáknak hívtok, azok a kristály gyerekek',
    'Szövetségbe forrt szabad köztársaságok, A nagy Oroszország kovácsolta frigy, A szovjet hatalma és egysége éljen, Sok nép így akarta s megalkotta így',
    'Fasszopó dagadt geci KFC t nem is így kell csinálni te  8 éves kis buzi﻿Fassz',
    'Kristálykisasszony',
    'A marokkói gyereknek a Lufthansa máris szerződést kínált!',
    'Lenovo Ideapad 520 - 15.6&quot; FullHD IPS, Core i5-7200U, 8GB, 1TB HDD, nVidia GeForce 940MX 4GB - Szürke laptop',
    'Kommunopoli',
    'Kőbányai Szopófantom',
    'Felfegyverzett pinyáta',
    'Rendőrruhába öltözött, kenőmájassal bekent dühös törpék',
    'Cheetost árulni 25 centért az iskolában',
    '#Csakpozitívan#békeszigete#victoryroyale',
    'Jestem polsky co kurwo mid or feed',
    'Gyógyszerre benzint',
    'Kerámia malacok, valamikor Krisztus előtt 600 körül készülhettek',
    'Csak egy árva páncélos hadosztály',
    '66 mental breakdown egymás után gec :)',
    'Fidel Catto',
    'Kaptár Music Pub Szórakozóhely, Dunaújváros',
    'Kit érdekel?',
    'Jézus megborítása, úgy hogy elmegyünk hozzá egy év múlva',
    'Radics Gigi megdobálása, majd ajándék CD visszakérése',
    'Danny Blue',
    'Megköszönni a buszsofőrnek, mielőtt kiugrasz',
    'Csattogós szárnyú falepke fizikai jellemzőinek tesztelése húzásra',
    'Az etióp esélyegyenlőségi ombucman',
    'Kokaint kevertem a miseborba!',
    'Közös belenézés, majd Tetétleni fantom megidézése',
    'Kevin a kocka',
    'Nyugat-Virginia',
    '287. esztergomi kutyaelnök- és passzívistasimogató klub',
    'Fekete-tenger kifehérítése és beszívás a tengerparton I. Kallixtusz Pápával',
    'Kassa visszafoglalása (majd ha belefér esetleg Pozsonyt is)',
    'Szupercsillagparaszt',
    'Bal-libsi média túlsúly',
    'Fagyasztott csirkefarhát hajigálás a Hősök terén',
    'Növényi kommunikáció és a mikorrhizagombák',
    'Deriválás',
    'Pornóapátin természetfilm forgatás',
    'Segédmotoros cicás brinyó',
    'Lánchídról leugrás majd Duna alján darezás fulladásig',
    'Egy doboló macska, aki Bongo névre hallgat',
    'Mikulás Kupa Székesfehérváron',
    'Amikor beüt az instant depresszió',
    'T-póz',
    'Svédország a PC-jét bányássza Bitcoin után. Lengyelország ennek láttán zavarodott',
    'Tyler1 Autizmus támadása',
    'Robika2002 istenítése a Keleti Pályaudvarban',
    'Közös ajtó törés Zolikával majd a pláza lebontása',
    'Állítsuk meg a Vegákat mozgalom (Legyen szíved, egyél követ)',
    'Adventi fényvillamos',
    'Mikrofondobáló  verseny',
    'Titok Paladin',
    'Pogó a lánywcben',
    'Apraja Falva Felnagyítása és Hókuszpók Leigázása',
    'Bolond Poloska',
    'Albán vírus',
    'Köszönjük Emese!',
    'Bácsalmás körtésítése, majd Sóstó édesítése',
    '0% THM',
    'Dögkút megásása, majd trinyó méregetés leonidasszal',
    'Kis Duna Sétány felnevelése, majd leitatása',
    'Egy kiló csirkefarháttal cápákat etetni a parkban',
    'A ludolacra tengeri állat, mely természetére és alakjára nézve, ahogy Arisztotelésznél olvashatjuk, igencsak csodálatra méltó. Négy szárnya van, s ezek a következőképpen helyezkednek el: kettő az arcán, kettő pedig a hátán van, s ezek által csodálatos gyorsasággal lebeg át egyik helyről a másikra, ahová csak kedve van eljutni',
    'Tojásrakó antilop',
    'Glutén összegyűjtése és likvidálása a Bermuda-háromszög felett',
    'Cigányzenét kérni streamen 1 dollárért',
    'Opportunity Marsjáró',
    'Tetris Battle Royal',
    'Grönland',
    'Pffffffffffffff nem rossz ez Mar nem erdekel de azert great lassan a 100000hez',
    'Egy meglepődött Pikachu',
    'Úgy meg tömtek,hogy már a számat sem tudom becsukni',
    'Anyukám spagettije',
    'Doofenshmirtz Gonosz RT',
    'Gyakorikérdések.hu',
    'Duolingo madár miközben elrabolja a családodat, mert kihagytad a német leckékdet ma',
    'Az 1666-os Londoni Tűzvész',
    'Édes otthon, Alabama',
    'Azok a rohadt fegyverre szerelhető, látást segítő lézerek',
    'Minecraft bébi teknős',
    'Gamer lány fürdővíz',
    'Meghalni a netherben.... Tizenötödjére...',
    'リ╎⊣⊣ᒷ∷ ⎓ᔑ⊣⊣𝙹ℸ ̣  ⎓⚍ᓵꖌ',
    'Danika House üvöltetése a 8. kerületben',
    'Egy orrszarvú bácsi',
    'Téliszalámi nyaraltatása majd szellemidézés a Pick gyárban',
    'Oh szar, itt jövünk megint',
    'Euro Truck Simulator 3',
    'Nincs Románia',
    'Enchantolt Aranyalma',
    'Naruto futás Széchenyi Térről árkádik Majd Közös Mekizés 2.0',
    'John Wick kutyája',
    'Átézi víz',
    'Howard az idegen',
    'Videoinfo1',
    'Én és a fiúk',
    'Időutazók',
    'Detektív Pikachu',
    'Feather Falling IV',
    'A híres neves bajai halászlé',
    'Természetesen Miskolc',
    'Kanadába emigrálás, hogy egy jobb életed legyen',
    'Rendben robbantó',
    'Arkangyal',
    'Nekifutásból basszuk pofán az összes nyomorék Manuel rajongót',
    'Bohém Rapszódia',
    'Fortnite feketelyuk',
    'Egy újabb sámán pakli, ami kurva broken',
    'Mort, a mókus',
    'Alza.hu',
    'Répát evő gömbhal',
    'Tesla Cyberturck',
    'Közös csokizás a 4-es villamoson a fiúlány ellenőrrel',
    'Arany Scar',
    'Ausztráliai erdőtűz',
    'A legközelebbi tárgy, ami tőled jobbra található',
    '2 órás erekció 2 perc alatt',
    'Vuhan',
    'Egy újabb Názi vs Zsidók társasjáték',
    'Egy gömbhal,ami répát eszik',
    'ASMR kézimunka, olajos és száraz DLC verziókkal',
    'Csak pörög a show, ide nem kell a szó, hashtag UNFIELD marad a nép',
    'Csöcsök és segg A KURVA ÉLET!',
    'Egirl.gg',
    'Minecraft szerver a BME gépészmérnökeinek',
    '200 guriga wc papír',
    '32 éves midget anyuka',
    '#Koronavíruskihívás',
    'HETE BRÉTÚRÓ A KURVA ANYÁD',
    'Erdőtűz Ausztráliában',
    'Tesi digitális oktatás',
    'Kijárási tilalom'
  ],
  black: [
    { text: 'lap szovege', cards: 1 },
    { text: 'Mi a legerősebb lap a Hearthstoneban?', cards: 1 },
    { text: '____, mi más bazdmeg!', cards: 1 },
    { text: 'Ez a ____ annyira m€gbo®!tott hogy l€€st€m a sz€kem®öl', cards: 1 },
    { text: '____ általi halál, a legszebb amit kívánhatsz', cards: 1 },
    { text: 'Mi kell egy jó matyizáshoz? ____', cards: 1 },
    { text: 'Ha a Föld nem lapos, magyarázd meg ezt: ____', cards: 1 },
    { text: '____ belépett a Terrorsita oldalra.', cards: 1 },
    { text: 'Nézd, most találtam ezt az új számot a Spotifyon, a neve ____', cards: 1 },
    { text: '2+2 az 4 -1 az ____', cards: 1 },
    { text: 'Mi történt Molnár Kikivel Bebaszós live közben? ____', cards: 1 },
    { text: '160 centi 40 kiló színtiszta erőszak: ____', cards: 1 },
    { text: '____ a városom.', cards: 1 },
    { text: '┴┬┴┤( ͡° ͜ʖ├┬┴┬ Psst, tesó, kérsz egy kis ____ -et?', cards: 1 },
    { text: 'Tesó nincs egy szál cigid? ____ -re kéne.', cards: 1 },
    { text: 'Milyen volt a házibuli? ____', cards: 1 },
    { text: 'Barát ilyet nem csinál: ____', cards: 1 },
    { text: '____ irtotta ki valójában a dinoszauruszokat.', cards: 1 },
    { text: '____-t kitiltotta a BattlEye', cards: 1 },
    { text: 'Oreo szopó kihívás w/ ____', cards: 1 },
    { text: '____ nem buzis, ha Zimbabwében történik.', cards: 1 },
    { text: '1994: A jövőben már repülő autóink lesznek.  2020:____', cards: 1 },
    { text: 'Pólók, pulcsik, bögrék, ____, Link a leírásban!', cards: 1 },
    { text: '____ , 1943, újraszínezve.', cards: 1 },
    { text: 'Haver: Be vagy rúgva? Én  (miközben próbálom elrejteni):  ____', cards: 1 },
    { text: 'Véletlen megdobáltam anyát ____-el a fürdőszobában, kitagadott otthonról érte. Lakhatok nálad egy ideig?', cards: 1 },
    { text: 'ZsozéAtya élő közvetítésbe kezdett: ____. Gyere, less be hozzá!', cards: 1 },
    { text: 'Hé haver, nem tudod véletlen, hogy mivel lehet távol tartani a fontoskodó törpéket, akik kiszabadultak a pincémből? De, ____-el!', cards: 1 },
    { text: 'Ó, a jó öreg ____!', cards: 1 },
    { text: 'Valójában ____ gyarmatosította Ausztráliát.', cards: 1 },
    { text: 'A 3. világháború kitörésének oka: ____', cards: 1 },
    { text: 'A legbiztonságosabb jelszó: ____', cards: 1 },
    { text: 'A telefonom vírust kapott miután letöltöttem egy ____ nevű alkalmazást.', cards: 1 },
    { text: 'Fortniteban a lámák mostantól ____-et is dobhatnak 30% eséllyel.', cards: 1 },
    { text: '____ egy igaz Náci', cards: 1 },
    { text: 'A Disney bejelentette, hogy a Shrek 5-ben biztosan lesz ____ is.', cards: 1 },
    { text: 'Aki meg akar ölni: ____ és aki megvéd ellene: ____', cards: 2 },
    { text: 'Kevin még ____-et is legyőzné karácsonykor 1 óra felkészülési idővel.', cards: 1 },
    { text: 'Emiatt a ____ miatt a a Záhony felől érkező vonat 20 percet késik.', cards: 1 },
    { text: '5000 új tagot számolhat ma az új társadalmi kísérlet, a jövőre induló 9. Keresztes Hadjárat expedíció, mert a szervezők ____-et ígértek a résztvevőknek díjul.', cards: 1 },
    { text: '10 év után végre kiderült, hogy Oroszország ____ miatt foglalta el a Krím-félszigetet.', cards: 1 },
    { text: '____ a buli lelke.', cards: 1 },
    { text: 'Crash Report: A VLC media player nem tudta megnyitni a ____.mp4 fájlt,  mert túl nagy volt a videó mérete.  Megjegyzés: Maximum 10 óra lehet.', cards: 1 },
    { text: 'Az EU a mémek után a ____-eket is bannolja 2021-ben', cards: 1 },
    { text: 'Megeszem a ____-et, ʰᵒᵍʸ ᵃⁿʸᵃ ˢᶻᵉʳᵉˢˢᵉⁿ ᵉⁿᵍᵉᵐ', cards: 1 },
    { text: '____ 5000 dollár támogatást küldött!', cards: 1 },
    { text: '____ : kommunista propaganda.', cards: 1 },
    { text: 'Az emberi százlábú következő tagja ____ lesz.', cards: 1 },
    { text: 'A ____ kitalálói maguktól ilyen idióták, vagy fogják a kezüket? Ekkora marhaságot.', cards: 1 },
    { text: 'Egy átlagos ember 8 ____-et nyel le álmában minden évben.', cards: 1 },
    { text: 'Momo ____-el fogja megölni ____-et a mai éjszaka folyamán, mert nem küldte tovább a körüzenetet!', cards: 2 },
    { text: 'Bipoláris zavarosként csak ____ segítségével lehet normális életet élni.', cards: 1 },
    { text: 'Belgiumnak szabadrúgást ítélt a  bíró Németország egyik játékosának szabálytalan ____-je miatt', cards: 1 },
    { text: 'Az autizmus nem létezik. Akiket ti autistáknak hívtok, azok a ____ gyerekek.', cards: 1 },
    { text: 'Apa: Miért áll a házunk előtt az FBI? ____', cards: 1 },
    { text: 'Sokkal több mint egy egyszerű hátizsák! Reagál az öléseinkre az új ____!', cards: 1 },
    { text: 'A szerver automatikusan kitiltott mert csúnya szót írtál a mondatodban. Azt mondtad: ____', cards: 1 },
    { text: '____-et a 2020-as Szigetre!', cards: 1 },
    { text: 'Első lecke: sohase támadj haragból. (megszagolja Alejandro ruháját.) Második lecke: gyere velem. Harmadik lecke: ____ Ezzel majd előkészítjük a negyediket: ____', cards: 2 },
    { text: 'Ezt a ____-et maga lucifer kovácsolta, vesznie kell!!!', cards: 1 },
    { text: '2021-től a köztelevízió M6-os csatornáján ____ témáju TV programok lesznek.', cards: 1 },
    { text: 'Mi leszel, ha nagy leszel? Én:____', cards: 1 },
    { text: 'Sárkány ellen sárkányfű, migráns ellen ____', cards: 1 },
    { text: 'Az új kutatások szerint a leggyakoribb állat Borsod megyében a ____', cards: 1 },
    { text: 'Annyira várom már a(z) ____ -t!', cards: 1 },
    { text: 'Figyelem! Üzletünkben a kiállított Samsung Galaxy Note 9 telefonon a ____ megszerzése NEM lehetséges! Megértésüket köszönjük!', cards: 1 },
    { text: 'Csak ____ élte túl a No Nut Novembert.', cards: 1 },
    { text: '____ még indukciós főzőlappal is kompatibilis', cards: 1 },
    { text: '____ keményebb mint az Aldiban a kenyér.', cards: 1 },
    { text: 'A ____ azt a madarat, amelyik a szarván pihen, hirtelen megragadja, megöli és felfalja', cards: 1 },
    { text: '3 ____ egy napra, az állatot távol tartja', cards: 1 },
    { text: 'Ben 10 új idegenének a neve: ____', cards: 1 },
    { text: 'Nagy akció az IKEA-ban! ____ , csak 16999 Ft-ért, Július 5-ig!', cards: 1 },
    { text: '____-ért cserébe  adok majd neked egy mekis almáspitét :)', cards: 1 },
    { text: 'A ____ megállítja a poloskákat.', cards: 1 },
    { text: 'Bevonták a Századvég folyóiratot egy kormánykritikus szólása miatt, ami ____ volt.', cards: 1 },
    { text: 'Spanyolország ____ miatt engedte el a Spanyol Szaharát 1976-ban.', cards: 1 },
    { text: 'Mit szállít az autó? Mit szállít az autó, kukásautó? ____-et.', cards: 1 },
    { text: 'Szóval, Hollandiában voltam nyaralni és kiordítottam a Hotel teraszán este 10 körül, nem hiszed el, de megjelent ____ tőle. Bár lehet csak a fű tette... Ki tudja.', cards: 1 },
    { text: 'Bemutatjuk a Google ____ -t!', cards: 1 },
    { text: 'Alexa, add hozzá a ____-et a bevásárlólistámra!', cards: 1 },
    { text: 'Hány éves vagyok, ha 1999-ben születtem? ____', cards: 1 },
    { text: '____ kimondhatja az N word-öt.', cards: 1 },
    { text: 'A Bosszúállok: Végjáték legjobb jelenete:____', cards: 1 },
    { text: '____ lélegzetelállító.', cards: 1 },
    { text: 'Az új hősnek Apex Legendsben az ultija: ____ és neve: ____', cards: 2 },
    { text: 'A 75 éves Helen Washington azért lőtt rá az unokájára, mert a teáscsészét ____ nélkül rakta le az asztalra.', cards: 1 },
    { text: 'Anya: MIÉRT SIKÍTASSZ?!! Én: ____', cards: 1 },
    { text: '____ a Szovjetuniót szolgálja.', cards: 1 },
    { text: '____ ____ segítségével fogja lerohanni az 51-es körzetet.', cards: 2 },
    { text: '____ az igazi Pro Gamer Mozdulat', cards: 1 },
    { text: '4 az sok? Az attól függ... ____? Nem. ____? Igen.', cards: 2 },
    { text: '____ ezt találta az 51-es körzetben: ____', cards: 2 },
    { text: '1994: A jövőben már repülő autóink lesznek.  2020: ____', cards: 1 },
    { text: 'Apa: Miért sírsz ennyire hangosan? Én: ____,', cards: 1 },
    { text: 'A Plague Inc. nevű játékban ____ -be még Grönlandnál is nehezebb bejutni', cards: 1 },
    { text: 'Minecraft 1.17: A ____ update', cards: 1 },
    { text: 'Ant-Man ____ segítségével győzi le Thanost az új Bosszúállókban.', cards: 1 },
    { text: '____ nagyobbat droppolt, mint a görög gazdaság.', cards: 1 },
    { text: 'Értesítjük tisztelt utasainkat,hogy a Szegedről Budapestre tartó vonat 8 órát késik ____ miatt. Megértésüket Köszönjük,a jegyeket nem váltjuk vissza...', cards: 1 },
    { text: '____ eléggé deszka, nem tudom te mit gondolsz róla. Azért basznám mondjuk.', cards: 1 },
    { text: 'Az új valóvilág nyertese: VV____', cards: 1 },
    { text: 'Ez a falusi 1 emeráldért 32 ____-et ad.', cards: 1 },
    { text: 'Rendelje meg most az új ____-et és ajándékba adunk mellé 2 búcsúcédulát is!', cards: 1 },
    { text: 'Mit modott PewDiePie a hídon? Már nem emlékszem.  ____', cards: 1 },
    { text: 'A Fortinte Season 10 legjobb skinje: ____, emótja:____ és csákánya:____.', cards: 3 },
    { text: 'Ki/Mi kezdte az ukrán polgárháborút? ____', cards: 1 },
    { text: 'Hivatalos! A NASA bejelentette a ____ 2-őt. Ez egy nagy előrelépés a tudományban!', cards: 1 },
    { text: '____ egy boomer', cards: 1 },
    { text: 'GTA RP-ben én egy ____ leszek, te pedig ____-et fogsz játszani.', cards: 2 },
    { text: 'A következő dolog, ami segíteni fog neked a 3. világháborúban: ____', cards: 1 },
    { text: '____ 20 millió fát ültet.', cards: 1 },
    { text: '____-től még Isten is kilépne az életnől.', cards: 1 },
    { text: 'Valami, ami mindig akkor tűnik el, amikor nagyon kéne: ____', cards: 1 },
    { text: 'Ami megvéd a besorozástól: ____', cards: 1 },
    { text: 'Amíg mindenki lerohanja az 51-es körzetet, addig mi lerohanjuk ____-et.', cards: 1 },
    { text: 'Pokimane turhája igazából egy ____ volt.', cards: 1 },
    { text: 'Közös főzés Elek Zoltánnal aztán közös ____.', cards: 1 },
    { text: 'Ninja holnaptól a www.____.com oldalon fog Fortnite-ot streamelni.', cards: 1 },
    { text: 'Odaszarnak és öntudatra kel: ____', cards: 1 },
    { text: '____ 20 millió fát ültet, hogy megakadályozza ____-et.', cards: 2 },
    { text: '____-től még Isten is kilépne az életből.', cards: 1 },
    { text: 'Egy ____ beleesett a folyóba ____ városban. Építsd meg a ____-t! HEY!', cards: 3 },
    { text: 'BREAKING NEWS! Megtalálták a koronavírus ellenszerét! ____! A tudósok nagyon meglepődtek.', cards: 1 },
    { text: 'John Wick a parabellumban ____-t ____-el gyilkolta meg.', cards: 2 },
    { text: 'Mi van a Chug Jugban? ____', cards: 1 },
    { text: '____ megölte a Lich Kinget.', cards: 1 },
    { text: 'Ha elfogy az összes wc papír, a legértékesebb dolog a járávny idejére a ____ lesz.', cards: 1 },
    { text: '2020 Január: 3. világháború, Február:Erdőtüzek, Március:Vírus, Április:____', cards: 1 }
  ]
}