export const cards = {
  name: 'Alap készlet',
  white: [
    'Öregemberszag',
    'Mikropénisz',
    'Használt bugyik',
    'Osztrály-sznob felhangok',
    'Leszarni Baranyát',
    'Telefonszex',
    'Egy tokaji borospincényi hulla',
    'A buzik',
    'Egy túlméretezett nyalóka',
    'Nyóckeres purdék',
    'Egy elcseszett mellpalsztika',
    'Egy macskahúggyal teletankolt vízágyú',
    'Egy jó kis Ödipusz-komplexus',
    'Egy picsányi póni',
    'Péniszirigység',
    'Orbán Viktor',
    'Soros György',
    'A doborulataim',
    'Félmeztelenül felébredni egy benzinkúton',
    'Szcientológia',
    'Öklendezés',
    'Paralgfűirtás',
    'Darth Vader',
    'A Danone görög joghurtos pornószínésznők',
    'Öregecske japán fickók',
    'Ingyenes kóstoló',
    'Ösztrogén',
    'Szexuális frusztráció',
    'Éhinség',
    'Egy kóbor fanszőr',
    'Pasik',
    'Szívfacsaró árvák',
    'Intim testékszer',
    'Egy szütyőnyi varázsbab',
    'Elnyomás',
    'Ügetés',
    'A kapcsolati állapootom',
    'Agyonkompenzálás',
    'Bepisilni',
    'EGy vöröske szelős herezacskója',
    'Herecsavarodás',
    'Maga az Ördög',
    'WoW',
    'Egy kis kibaszott béke és nyugalom',
    'Robo-Hitler',
    'Cicifotók',
    'Gyengéd simi a bikinivonalon',
    'Kitörölni a csajod seggét',
    'Lance Armstrong hiányzó heréje',
  ],
  black: [
    'Hogyan vesztettem el a szűzességem?',
    'Miért nem jön álom a szememre?',
    'Mi ez a szag?',
    'Lehet, hogy veleszületett.... Lehet, hogy ____.',
    'Mi jár a Happy Meal mellé?',
    'Kár, hogy a mai gyerekek csak a ____-ra/re tudnak gondolni.',
    'Salvadort Dali gyermekkori képeinek százai szólnak ____-ról/ről.',
    'A legújabb  alternatív gyógymód már kihasználja a(z) ____ gyógyító erejét.',
    'Mi ez a hang?',
    'Mi vetett véget a legutolsó kapcsolatomnak?',
    'Iszom, hogy felejtsem: ____.',
    'Mi Batman titkos fétise?',
    'Apu, miért sír anyu?',
    'Egy gondolat bánt enegemet: ____ által halni meg.',
    'A következő bűvészmutatványomban elővarázsolom ____-t ____-ból/ből.',
    'Elnézést tanár úr, de nincs kész a házifeladatom ____ miatt.',
  ]
}


export const cards2 = {
  name: 'b',
  white: [
    'Magyarország',
    'Az ex feleségem',
    'Szexi párnacsaták',
    'Egy újabb kibaszott csillámvámpíros film',
    'Kibernetikus implantációk',
    'Civil áldozatok',
    'A női orgazmus',
    'Ribancok',

  ],
  black: [
    'Szex közben szeretek a ____-ra/re gondolni',
    'Mit rejtegetnek előlem a szüleim?',
    'Mi biztosít garantált szexet?',
    'A reptéri biztonsági előírások monstantól megtiltják a ____ fedélzetre vitelét',
  ]
}